### PR TITLE
Fix build and all deprecation warnings on Python 3.

### LINKED ISSUE #10: Fails to build on Python 3 with errors about PyInt_AS_LONG (with certain compiler options)
The compiler produces these errors:
```
    zopyx/txng3/ext/python-Levenshtein-0.10/Levenshtein.c:1374:27: error: implicit declaration of function 'PyInt_AS_LONG' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ops[i].spos = (size_t)PyInt_AS_LONG(item);
                              ^
    zopyx/txng3/ext/python-Levenshtein-0.10/Levenshtein.c:1416:28: error: implicit declaration of function 'PyInt_AS_LONG' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        bops[i].sbeg = (size_t)PyInt_AS_LONG(item);
                               ^
    zopyx/txng3/ext/python-Levenshtein-0.10/Levenshtein.c:1487:20: error: implicit declaration of function 'PyInt_AS_LONG' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        long int len = PyInt_AS_LONG(object);
```

`PyInt_AS_LONG` was removed in Python 3; the replacement is `PyLong_AS_LONG`, which is just a define for the function call  `PyLong_AsLong(op)`.

When I did the initial port to Python 3, these would have been logged as warnings (which of course pip hides), but they do mean that uses of the function (module?) that contain them would fail. I was using a different compiler here (`ccache`) that explicitly asked for those warnings to be errors.

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #10.

This updates the package to use the new-in-Python-3 unicode APIs when available. Previously there were ~50 deprecation warnings. Now there are none.

This also converts most uses of `size_t` into `Py_ssize_t`, because that's what the Python APIs use and return (e.g., for unicode length, sequence length, etc). This eliminates more warnings and casts.

### CODE REVIEW

**Comment by jamadden** [comment]
travis-ci.org is shutting down so there's currently no CI running on PRs here. I have tested it locally with Python 2.7, 3.5 and 3.9.

**Comment by jamadden** [comment]
Hi @zopyx ! I haven't been around for awhile, but this patch is becoming more important. Without it, it doesn't compile on Python 3.12 at all (though I will still need to make one adjustment for 3.12, which I can add to this PR). Any hope of getting this released anytime soon?

**Comment by jamadden** [comment]
My latest commit adds support for the newer versions of Python, while still being compatible back to Python 2.7.

There are remaining warning about the pre-ANSI C code in `hashtable.c`. It is still using the no-definition function definitions. This is likely to eventually be unsupported by any compilers.
```C
void
hashtable_destroy(table, del)
	hashtable	*table;
	int			 del;
{
}
```

Instead of the standard 
```C
void
hashtable_destroy(hashtable* table, int del)
{
}
```

**Comment by zopyx** [comment]
Hi there,

the project is unmaintained and dead since 2019:

https://community.plone.org/t/textindexng3-end-of-lifetime-announcement/8111

I recommend to fork the repo. 
If you want to create a new release on PyPI, I can grant you the related access rights.

**Comment by jamadden** [comment]
Thanks, I understand this is unmaintained. In our case, we need it for legacy code that we're currently modernizing, with hopes to eventually drop it. 

I'd be more than happy to fork the project and publish an updated version to PyPI if you'd give me the rights. I can't promise any more maintenance after that, but hopefully that's helpful.
